title: code;
description: My Personal Code Repository
author: Batuhan Saygin
github: https://github.com/batuhansaygin
about: I am a software engineering student. Currently doing more in backend, focused in Python and Django.
disqus_shortname: coderepository
google_analytics: UA-104900009-4
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/batuhansaygin"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/6426428"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/batuhansaygin"

share:
  twitter_username: #
  fb_appid: #

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://batuhansaygin.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
